version: '3.7'

services:

  linto-platform-mongodb-migration:
    image: lintoai/linto-platform-mongodb-migration:latest
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    command: # Overrides CMD specified in dockerfile (none here, handled by entrypoint)
      - --run-cmd=npm run migrate
    env_file: .docker_env
    volumes:
      - ${LINTO_SHARED_MOUNT}/${LINTO_STACK_MONGODB_SHARED_SCHEMAS}/:/usr/src/app/linto-platform-mongodb-migration/migrations/shared/
    ports:
      - 80:80

networks:
  internal:
